import { ArrowDown, ArrowUp, ArrowUpDown, Pencil, Power, Trash2 } from "lucide-react";
import type { SortOrder, Tarjeta, TarjetaSortColumn } from "@/api/tarjetas";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";
import { TARJETA_ICON_COMPONENTS } from "@/lib/tarjeta-iconos";

export function TarjetasTable({ rows, sort, onSort, onEdit, onToggle, onDelete }: { rows: Tarjeta[]; sort: { column: TarjetaSortColumn; order: SortOrder } | null; onSort: (column: TarjetaSortColumn) => void; onEdit: (row: Tarjeta) => void; onToggle: (row: Tarjeta) => void; onDelete: (row: Tarjeta) => void; }) {
  if (!rows.length) return <EmptyState title="Sin tarjetas" description="No hay tarjetas registradas o no coinciden con los filtros."/>;
  const Header = ({ id, children }: { id: TarjetaSortColumn; children: React.ReactNode }) => { const active = sort?.column === id; return <th className="px-4 py-3"><button className="inline-flex items-center gap-1" onClick={() => onSort(id)}>{children}{active ? sort.order === "asc" ? <ArrowUp className="h-4 w-4"/> : <ArrowDown className="h-4 w-4"/> : <ArrowUpDown className="h-4 w-4 opacity-50"/>}</button></th>; };
  return <div className="overflow-x-auto rounded-md border bg-card"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-muted text-xs uppercase text-muted-foreground"><tr><Header id="sedeId">Sede</Header><Header id="numero">Numero</Header><Header id="color">Color</Header><Header id="icono">Icono</Header><th className="px-4 py-3">Areas</th><Header id="activo">Estado</Header><Header id="enUso">Uso</Header><th className="px-4 py-3">Acciones</th></tr></thead><tbody className="divide-y">{rows.map((row) => { const Icon = TARJETA_ICON_COMPONENTS[row.icono]; return <tr key={row.id}><td className="px-4 py-3"><span className="font-medium">{row.sedeNombre}</span><span className="block text-xs text-muted-foreground">{row.empresaNombre}</span></td><td className="px-4 py-3 font-semibold">{row.numero}</td><td className="px-4 py-3"><span className="inline-flex items-center gap-2"><span className="h-6 w-6 rounded border" style={{ backgroundColor: row.color }}/>{row.color}</span></td><td className="px-4 py-3"><span className="inline-flex items-center gap-2"><Icon className="h-5 w-5"/>{row.icono}</span></td><td className="px-4 py-3">{row.areas.map((a) => a.nombre).join(", ")}</td><td className="px-4 py-3"><Badge variant={row.activo ? "success" : "danger"}>{row.activo ? "Activo" : "Inactivo"}</Badge></td><td className="px-4 py-3"><Badge variant={row.enUso ? "warning" : "info"}>{row.enUso ? "En uso" : "Disponible"}</Badge></td><td className="px-4 py-3"><div className="flex gap-2"><button title="Editar" onClick={() => onEdit(row)}><Pencil className="h-4 w-4"/></button><button disabled={row.enUso} title={row.enUso ? "No se puede cambiar el estado mientras esta en uso" : row.activo ? "Desactivar" : "Activar"} className="disabled:opacity-30" onClick={() => onToggle(row)}><Power className="h-4 w-4"/></button><button disabled={row.enUso} title={row.enUso ? "No se puede eliminar mientras esta en uso" : "Eliminar"} className="text-destructive disabled:opacity-30" onClick={() => onDelete(row)}><Trash2 className="h-4 w-4"/></button></div></td></tr>; })}</tbody></table></div>;
}
