import { useState } from "react";
import { ArrowDown,ArrowUp,ArrowUpDown,ChevronDown,Search } from "lucide-react";
import { AprobacionBadge } from "@/components/visitas/AprobacionBadge";
import { Button } from "@/components/ui/button";
import { Dialog } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { useRegisterPorteriaRefresh } from "@/context/PorteriaRefreshContext";
import { useEncargadoVisitaHistory } from "@/hooks/useEncargadoVisita";
import type { EncargadoVisitaHistoryQuery,EncargadoVisitaRecord } from "@/api/encargadoVisita";

const columns:Array<{id:NonNullable<EncargadoVisitaHistoryQuery["sortBy"]>;label:string}>=[{id:"id",label:"Visita"},{id:"visitante",label:"Visitante"},{id:"documento",label:"Documento"},{id:"empresa",label:"Empresa"},{id:"motivo",label:"Motivo"},{id:"entradaAt",label:"Fecha"}];

export default function EncargadoVisitaHistorialPage(){
 const h=useEncargadoVisitaHistory(),[advanced,setAdvanced]=useState(false),[selected,setSelected]=useState<EncargadoVisitaRecord|null>(null);
 useRegisterPorteriaRefresh(h.refresh,h.loading);
 const pages=Math.max(1,Math.ceil(h.total/h.limit)),from=h.total?(h.page-1)*h.limit+1:0,to=Math.min(h.page*h.limit,h.total);
 const update=(key:string,value:string)=>h.setDraft({...h.draft,[key]:value||undefined});
 return <section className="space-y-4">
  <div className="rounded-md border bg-card p-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={h.draft.search??""} onChange={e=>update("search",e.target.value)} placeholder="Buscar en todos los campos..." className="pl-9 pr-10"/><button type="button" className="absolute right-1 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center" onClick={()=>setAdvanced(v=>!v)} aria-label="Mostrar búsqueda avanzada"><ChevronDown className={`h-4 w-4 ${advanced?"rotate-180":""}`}/></button></div>
   {advanced?<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[["visitante","Visitante"],["documento","Documento"],["empresa","Empresa"],["motivo","Motivo"]].map(([key,label])=><label key={key} className="space-y-1 text-sm"><span className="text-muted-foreground">{label}</span><Input value={String(h.draft[key as keyof typeof h.draft]??"")} onChange={e=>update(key,e.target.value)}/></label>)}<label className="space-y-1 text-sm"><span className="text-muted-foreground">Desde</span><Input type="date" value={h.draft.entradaFrom??""} onChange={e=>update("entradaFrom",e.target.value)}/></label><label className="space-y-1 text-sm"><span className="text-muted-foreground">Hasta</span><Input type="date" value={h.draft.entradaTo??""} onChange={e=>update("entradaTo",e.target.value)}/></label></div>:null}
   <div className="mt-3 flex justify-end"><Button size="sm" onClick={h.apply}><Search className="mr-1 h-4 w-4"/>Buscar</Button></div>
  </div>
  {h.error?<p className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{h.error}</p>:null}
  {h.loading?<p className="rounded-xl border p-8 text-center text-sm text-muted-foreground">Cargando historial...</p>:<div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-muted/60"><tr>{columns.map(c=><th key={c.id} className="px-4 py-3"><button className="flex items-center gap-1" onClick={()=>h.toggleSort(c.id)}>{c.label}{h.sort.sortBy===c.id?(h.sort.sortOrder==="asc"?<ArrowUp className="h-4 w-4"/>:<ArrowDown className="h-4 w-4"/>):<ArrowUpDown className="h-4 w-4 opacity-50"/>}</button></th>)}<th className="px-4 py-3">Aprobación</th></tr></thead><tbody>{h.items.map(v=><tr key={v.id} className="cursor-pointer border-t hover:bg-muted/40" onClick={()=>setSelected(v)}><td className="px-4 py-3">#{v.id}</td><td className="px-4 py-3 font-medium">{v.visitante}</td><td className="px-4 py-3">{v.documento}</td><td className="px-4 py-3">{v.empresa??"—"}</td><td className="px-4 py-3">{v.motivo}</td><td className="px-4 py-3">{v.entradaAt?new Date(v.entradaAt).toLocaleString("es-PY"):"—"}</td><td className="px-4 py-3"><AprobacionBadge estado={v.estadoAprobacion} motivoRechazo={v.motivoRechazo}/></td></tr>)}</tbody></table>{!h.items.length?<p className="p-8 text-center text-muted-foreground">Sin historial.</p>:null}</div>}
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3 text-sm text-muted-foreground"><span>Mostrar por página</span><Select className="w-24" value={h.limit} onChange={e=>{h.setLimit(Number(e.target.value));h.setPage(1);}}>{[15,50,100].map(n=><option key={n}>{n}</option>)}<option value={Math.max(h.total,1)}>Todos</option></Select><span>Mostrando {from} - {to} de {h.total} elementos</span></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" disabled={h.page<=1} onClick={()=>h.setPage(h.page-1)}>Anterior</Button><span className="text-sm">Página {h.page} de {pages}</span><Button variant="outline" size="sm" disabled={h.page>=pages} onClick={()=>h.setPage(h.page+1)}>Siguiente</Button></div></div>
  <Dialog open={selected!==null} onOpenChange={o=>{if(!o)setSelected(null);}} title={selected?`Visita #${selected.id}`:"Visita"} description="Detalle de la visita">{selected?<dl className="grid gap-3 sm:grid-cols-2">{[["Visitante",selected.visitante],["Documento",selected.documento],["Empresa",selected.empresa??"—"],["Motivo",selected.motivo],["Sede",selected.sedeNombre]].map(([k,v])=><div key={k} className="rounded-md border p-3"><dt className="text-xs text-muted-foreground">{k}</dt><dd className="font-medium">{v}</dd></div>)}<div className="rounded-md border p-3"><dt className="text-xs text-muted-foreground">Aprobación</dt><dd className="mt-1"><AprobacionBadge estado={selected.estadoAprobacion} motivoRechazo={selected.motivoRechazo}/></dd></div>{selected.estadoAprobacion==="rechazada"?<div className="rounded-md border p-3 sm:col-span-2"><dt className="text-xs text-muted-foreground">Motivo del rechazo</dt><dd className="font-medium">{selected.motivoRechazo}</dd></div>:null}</dl>:null}</Dialog>
 </section>;
}
