import { useState } from "react";
import { Check,ChevronDown,Clock3,X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useRegisterPorteriaRefresh } from "@/context/PorteriaRefreshContext";
import { useEncargadoVisitaSummary } from "@/hooks/useEncargadoVisita";
import type { EncargadoVisitaRecord,EstadoAprobacion } from "@/api/encargadoVisita";

const LABEL:Record<EstadoAprobacion,string>={pendiente:"Pendiente",aprobada:"Aprobada",rechazada:"Rechazada"};
function VisitCard({visit,onDecide}:{visit:EncargadoVisitaRecord;onDecide:(id:number,s:"aprobada"|"rechazada")=>Promise<void>}){
 const [saving,setSaving]=useState(false); const act=async(s:"aprobada"|"rechazada")=>{setSaving(true);try{await onDecide(visit.id,s);}finally{setSaving(false);}};
 return <article className="rounded-xl border bg-card p-4 shadow-soft"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{visit.visitante}</p><p className="truncate text-sm text-muted-foreground">{visit.empresa??"—"} · {LABEL[visit.estadoAprobacion]}</p></div><Badge variant={visit.estadoAprobacion==="aprobada"?"success":visit.estadoAprobacion==="rechazada"?"danger":"warning"}>{LABEL[visit.estadoAprobacion]}</Badge></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><p><span className="text-muted-foreground">Motivo:</span> {visit.motivo}</p><p><span className="text-muted-foreground">Sede:</span> {visit.sedeNombre}</p><p className="flex items-center gap-1"><Clock3 className="h-4 w-4"/>{visit.entradaAt?new Date(visit.entradaAt).toLocaleTimeString("es-PY",{hour:"2-digit",minute:"2-digit"}):"—"}</p></div>{visit.estadoAprobacion!=="aprobada"?<div className="mt-4 flex gap-2"><Button size="sm" disabled={saving} onClick={()=>void act("aprobada")}><Check className="mr-1 h-4 w-4"/>Aprobar</Button>{visit.estadoAprobacion==="pendiente"?<Button size="sm" variant="outline" disabled={saving} onClick={()=>void act("rechazada")}><X className="mr-1 h-4 w-4"/>Rechazar</Button>:null}</div>:null}</article>;
}
function Section({title,visits,onDecide}:{title:string;visits:EncargadoVisitaRecord[];onDecide:(id:number,s:"aprobada"|"rechazada")=>Promise<void>}){return <section className="space-y-3"><h2 className="font-semibold">{title} <span className="text-muted-foreground">({visits.length})</span></h2>{visits.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{visits.map(v=><VisitCard key={v.id} visit={v} onDecide={onDecide}/>)}</div>:<p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No hay visitas en esta sección.</p>}</section>}
export default function EncargadoVisitaPage(){const {data,loading,error,refresh,decide}=useEncargadoVisitaSummary();const [rejectedOpen,setRejectedOpen]=useState(false);useRegisterPorteriaRefresh(refresh,loading);const approved=data.visits.filter(v=>v.estadoAprobacion==="aprobada"),pending=data.visits.filter(v=>v.estadoAprobacion==="pendiente"),rejected=data.visits.filter(v=>v.estadoAprobacion==="rechazada");return <div className="space-y-6">{error?<p className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<section className="grid gap-3 sm:grid-cols-3">{[["Tus visitas hoy",data.metrics.today],["Visitas aprobadas",data.metrics.approved],["Visitas por aprobar",data.metrics.pending]].map(([label,value])=><article key={String(label)} className="rounded-xl border bg-card p-4 shadow-soft"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold tabular-nums">{value}</p></article>)}</section>{loading?<p className="rounded-xl border p-8 text-center text-sm text-muted-foreground">Cargando visitas...</p>:<><Section title="Visitas aprobadas" visits={approved} onDecide={decide}/><Section title="Por aprobar" visits={pending} onDecide={decide}/><section className="space-y-3"><button type="button" className="flex w-full items-center justify-center gap-2 rounded-md border bg-card p-3 text-sm font-medium" onClick={()=>setRejectedOpen(v=>!v)} aria-expanded={rejectedOpen}>Visitas rechazadas ({rejected.length})<ChevronDown className={`h-4 w-4 transition-transform ${rejectedOpen?"rotate-180":""}`}/></button>{rejectedOpen?<Section title="Rechazadas" visits={rejected} onDecide={decide}/>:null}</section></>}</div>}
