import { ArrowDown, ArrowUp, ArrowUpDown, Pencil, Power, Trash2 } from "lucide-react";
import type { Area, AreaSortColumn, SortOrder } from "@/api/areas";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/empty-state";

export function AreasTable({ rows, sort, onSort, onEdit, onToggle, onDelete }: { rows: Area[]; sort: { column: AreaSortColumn; order: SortOrder } | null; onSort: (column: AreaSortColumn) => void; onEdit: (row: Area) => void; onToggle: (row: Area) => void; onDelete: (row: Area) => void; }) {
  if (!rows.length) return <EmptyState title="Sin areas" description="No hay areas registradas o no coinciden con los filtros."/>;
  const Header = ({ id, children }: { id: AreaSortColumn; children: React.ReactNode }) => { const active = sort?.column === id; return <th className="px-4 py-3"><button className="inline-flex items-center gap-1" onClick={() => onSort(id)}>{children}{active ? sort.order === "asc" ? <ArrowUp className="h-4 w-4"/> : <ArrowDown className="h-4 w-4"/> : <ArrowUpDown className="h-4 w-4 opacity-50"/>}</button></th>; };
  return <div className="overflow-hidden rounded-md border bg-card"><table className="w-full text-left text-sm"><thead className="bg-muted text-xs uppercase text-muted-foreground"><tr><Header id="id">ID</Header><Header id="sedeId">Sede</Header><Header id="nombre">Nombre</Header><Header id="activo">Estado</Header><th className="px-4 py-3">Acciones</th></tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row.id}><td className="px-4 py-3">{row.id}</td><td className="px-4 py-3"><span className="font-medium">{row.sedeNombre}</span><span className="block text-xs text-muted-foreground">{row.empresaNombre}</span></td><td className="px-4 py-3 font-medium">{row.nombre}</td><td className="px-4 py-3"><Badge variant={row.activo ? "success" : "danger"}>{row.activo ? "Activo" : "Inactivo"}</Badge></td><td className="px-4 py-3"><div className="flex gap-2"><button title="Editar" onClick={() => onEdit(row)}><Pencil className="h-4 w-4"/></button><button title={row.activo ? "Desactivar" : "Activar"} onClick={() => onToggle(row)}><Power className="h-4 w-4"/></button><button title="Eliminar" className="text-destructive" onClick={() => onDelete(row)}><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>;
}
